server:
  port: 8085

spring:
  profiles:
    active: dev

  #jpa
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect